import numpy as np
from scipy.optimize import least_squares
from .generate import generate_helix_ca_by_crick
from ..util import _construct_param_vector


def _residuals_for_fit_helix_by_crick(
    params: np.ndarray, ca_coord_obs: np.ndarray, parse_dict: dict, **kwargs
):
    """
    Return the residuals between observed CA coordinates and those generated by Crick helix parameters.

    Parameters
    ----------
    params : np.ndarray
        Flattened parameter vector.
    ca_coord_obs : np.ndarray
        Observed CA coordinates.
    parse_dict : dict
        Dictionary mapping parameter names to their indices or slices in the params vector.
    kwargs : dict
        Additional fixed parameters for helix generation.
    """

    param_kwargs = {}
    for key, value in parse_dict.items():
        param_kwargs[key] = params[value]
    pred_ca, _ = generate_helix_ca_by_crick(**param_kwargs, **kwargs)
    coord_diff = pred_ca - ca_coord_obs
    residuals = []
    for diff in coord_diff:
        residuals.extend([np.sqrt(np.sum(diff**2))])
    return residuals


def _optimize_helix_by_crick(
    ca_coords_obs: np.ndarray,
    initial_params: dict,
    param_names_to_optimize: list[str],
):

    lb_params = dict(
        centroid=(-np.inf, -np.inf, -np.inf),
        direction=(-1.0, -1.0, -1.0),
        radius=2.0,
        omega=1.5,
        pitch_angle=-np.pi,
        phi0=-np.pi,
    )
    ub_params = dict(
        centroid=(np.inf, np.inf, np.inf),
        direction=(1.0, 1.0, 1.0),
        radius=7.0,
        omega=2.0,
        pitch_angle=np.pi,
        phi0=np.pi,
    )

    p0, parse_dict = _construct_param_vector(initial_params, param_names_to_optimize)
    lb, _ = _construct_param_vector(lb_params, param_names_to_optimize)
    ub, _ = _construct_param_vector(ub_params, param_names_to_optimize)
    fixed_params = initial_params.copy()
    for name in param_names_to_optimize:
        fixed_params.pop(name, None)
    assert (
        len(p0) == len(lb) == len(ub)
    ), "Parameter vector and bounds must have the same length."
    kwargs = dict(parse_dict=parse_dict)
    kwargs.update(fixed_params)
    result = least_squares(
        _residuals_for_fit_helix_by_crick,
        p0,
        bounds=(lb, ub),
        args=[ca_coords_obs],
        kwargs=kwargs,
        method="trf",
        max_nfev=10000,
    )
    if not result.success:
        raise ValueError("Crick helix fitting failed with message:\n" + result.message)
    params = result.x
    optimized_params = {}
    for name, value in parse_dict.items():
        optimized_params[name] = params[value]
    final_params = optimized_params.copy()
    final_params.update(fixed_params)
    final_params["direction"] /= np.linalg.norm(final_params["direction"])
    return final_params, result


def fit_helix_by_crick(
    ca_coords_obs: np.ndarray,
    residue_num=None,
    centroid=None,
    direction=None,
    radius=2.26,
    omega=4 * np.pi / 7,
    pitch_angle=0.358,
    phi0=0.0,
    params_not_to_fit: list[str] = [],
    verbose: bool = False,
):
    """
    Fit a Crick helix to the observed CA coordinates.

    Parameters
    -----------------
    - observed_ca: np.ndarray - The coordinates of the CA atoms to fit.
    - initial_params: dict - Initial parameters for the helix fitting.
    - params_not_to_fit: list[str], default [] - Parameter names held fixed
      during all optimization stages (pinned to their initial values).


    Returns
    -----------------
    - params : dict
        Fitted parameters of the helix.
    - rmsd : float
        The root mean square deviation (RMSD) between the observed and fitted CA coordinates.
    - xyz : np.ndarray
        The coordinates of the fitted helix CA atoms.
    """

    def _log(message: str):
        if verbose:
            print(f"[fit_helix_by_crick] {message}")

    initial_params = {}
    residue_num = residue_num if residue_num is not None else ca_coords_obs.shape[0]
    initial_params["residue_num"] = residue_num
    initial_params["centroid"] = (
        centroid if centroid is not None else np.mean(ca_coords_obs, axis=0)
    )
    initial_params["direction"] = (
        direction if direction is not None else ca_coords_obs[-1] - ca_coords_obs[0]
    )
    initial_params["direction"] /= np.linalg.norm(initial_params["direction"])
    initial_params["radius"] = radius
    initial_params["omega"] = omega
    initial_params["pitch_angle"] = pitch_angle
    initial_params["phi0"] = phi0

    # 每个 stage 要优化的参数名; 固定参数 (params_not_to_fit) 逐 stage 剔除,
    # 某个 stage 全被固定时跳过 (least_squares 不接受空参数向量)。
    stages = [
        ("Stage 0/2: optimize direction", ["direction"]),
        ("Stage 1/2: optimize centroid", ["centroid"]),
    ]
    for i in range(10):
        stages.append((
            f"Refinement iteration {i + 1}/10: local geometric terms",
            ["radius", "omega", "pitch_angle", "phi0"],
        ))
        stages.append((
            f"Refinement iteration {i + 1}/10: joint parameter update",
            ["centroid", "direction", "radius", "omega", "pitch_angle", "phi0"],
        ))

    stage_params = initial_params   # 所有 stage 都被跳过时保持初值不动
    result = None
    for label, names in stages:
        names = [name for name in names if name not in params_not_to_fit]
        if not names:
            _log(f"{label}: skipped (all fixed)")
            continue
        _log(label)
        stage_params, result = _optimize_helix_by_crick(
            ca_coords_obs=ca_coords_obs,
            initial_params=stage_params,
            param_names_to_optimize=names,
        )

    if result is None:
        # 所有参数都被固定: 没有优化可跑, 直接对当前参数求 RMSD。
        pred_ca, _ = generate_helix_ca_by_crick(**stage_params)
        rmsd = np.sqrt(np.sum((pred_ca - ca_coords_obs) ** 2) / residue_num)
    else:
        rmsd = np.sqrt(np.sum(result.fun**2) / residue_num)
    xyz, params = generate_helix_ca_by_crick(**stage_params)
    _log(f"Fit completed with RMSD={rmsd:.4f}")
    return params, rmsd, xyz
